// Auto-generated by generate_n8n.py — do not edit manually.
import type {
	IAuthenticateGeneric,
	ICredentialTestRequest,
	ICredentialType,
	INodeProperties,
} from 'n8n-workflow';

export class ProiectroApi implements ICredentialType {
	name = 'proiectroApi';
	displayName = 'Proiect.ro API';
	icon = { light: 'file:proiectro.svg', dark: 'file:proiectro.svg' } as const;
	documentationUrl = 'https://proiect.ro/api/v1/docs';

	properties: INodeProperties[] = [
		{
			displayName: 'API Key',
			name: 'apiKey',
			type: 'string',
			typeOptions: { password: true },
			default: '',
			required: true,
			description: 'Your Proiect.ro API key (found in Settings > API Keys)',
		},
		{
			displayName: 'Workspace Path',
			name: 'workspacePath',
			type: 'string',
			default: '',
			required: true,
			description:
				'Your workspace identifier (the path segment in your Proiect.ro URL)',
		},
		{
			displayName: 'Base URL',
			name: 'baseUrl',
			type: 'string',
			default: 'https://proiect.ro',
			description:
				'The Proiect.ro instance URL (change only for self-hosted)',
		},
	];

	authenticate: IAuthenticateGeneric = {
		type: 'generic',
		properties: {
			headers: {
				Authorization: '=Bearer {{$credentials.apiKey}}',
				Accept: 'application/json',
			},
		},
	};

	test: ICredentialTestRequest = {
		request: {
			baseURL: '={{$credentials.baseUrl}}/api/v1/{{$credentials.workspacePath}}',
			url: '/team',
			method: 'GET',
		},
	};
}
