// Auto-generated by generate_n8n.py — do not edit manually.
import type { INodeProperties } from 'n8n-workflow';

export const contactOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: { resource: ['contact'] },
		},
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a contact',
				description: 'Add a contact to an organization',
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a contact',
				description: 'Delete a contact',
			},
			{
				name: 'Invite to Portal',
				value: 'invite',
				action: 'Invite a contact to portal',
				description: 'Send a portal invitation to a contact',
			},
			{
				name: 'List',
				value: 'list',
				action: 'List contacts',
				description: 'List contacts for an organization',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a contact',
				description: 'Update a contact\'s details',
			},
		],
		default: 'create',
	},
];

export const contactFields: INodeProperties[] = [
	{
		displayName: 'Org Name or ID',
		name: 'org_id',
		type: 'options',
		required: true,
		typeOptions: {
			loadOptionsMethod: 'getCustomers',
		},
		default: '',
		displayOptions: {
			show: {
				resource: ['contact'],
				operation: ["list", "create", "update", "delete", "invite"],
			},
		},
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
	},
	{
		displayName: 'Contact Info First Name',
		name: 'contact_info_first_name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['contact'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Contact Info Last Name',
		name: 'contact_info_last_name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['contact'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Contact Info Email',
		name: 'contact_info_email',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['contact'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Contact Info Phone',
		name: 'contact_info_phone',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['contact'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Contact Info Address',
		name: 'contact_info_address',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['contact'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Contact Info Job Title',
		name: 'contact_info_job_title',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['contact'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Contact ID',
		name: 'contact_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['contact'],
				operation: ["update", "delete", "invite"],
			},
		},
	},
];
