// Auto-generated by generate_n8n.py — do not edit manually.
import type { INodeProperties } from 'n8n-workflow';

export const labelOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: { resource: ['label'] },
		},
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a label',
				description: 'Create a new label',
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a label',
				description: 'Delete a label',
			},
			{
				name: 'Label Customer',
				value: 'label_customer',
				action: 'Label a customer',
				description: 'Attach a label to a customer',
			},
			{
				name: 'Label Member',
				value: 'label_member',
				action: 'Label a team member',
				description: 'Attach a label to a team member',
			},
			{
				name: 'Label Operational Work Item',
				value: 'label_operational_item',
				action: 'Label an operational work item',
				description: 'Attach a label to an operational work item',
			},
			{
				name: 'Label Proposal',
				value: 'label_proposal',
				action: 'Label a proposal',
				description: 'Attach a label to a proposal',
			},
			{
				name: 'Label Resource',
				value: 'label_resource',
				action: 'Label a resource',
				description: 'Attach a label to a resource',
			},
			{
				name: 'Label Work Item',
				value: 'label_work_item',
				action: 'Label a work item',
				description: 'Attach a label to a project work item',
			},
			{
				name: 'List All',
				value: 'list',
				action: 'List all labels',
				description: 'List all labels in the workspace',
			},
			{
				name: 'Unlabel Customer',
				value: 'unlabel_customer',
				action: 'Unlabel a customer',
				description: 'Remove a label from a customer',
			},
			{
				name: 'Unlabel Member',
				value: 'unlabel_member',
				action: 'Unlabel a team member',
				description: 'Remove a label from a team member',
			},
			{
				name: 'Unlabel Operational Work Item',
				value: 'unlabel_operational_item',
				action: 'Unlabel an operational work item',
				description: 'Remove a label from an operational work item',
			},
			{
				name: 'Unlabel Proposal',
				value: 'unlabel_proposal',
				action: 'Unlabel a proposal',
				description: 'Remove a label from a proposal',
			},
			{
				name: 'Unlabel Resource',
				value: 'unlabel_resource',
				action: 'Unlabel a resource',
				description: 'Remove a label from a resource',
			},
			{
				name: 'Unlabel Work Item',
				value: 'unlabel_work_item',
				action: 'Unlabel a work item',
				description: 'Remove a label from a project work item',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a label',
				description: 'Update a label',
			},
		],
		default: 'create',
	},
];

export const labelFields: INodeProperties[] = [
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['label'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Label Type',
		name: 'label_type',
		type: 'options',
		options: [
			{ name: 'Date', value: 'date' },
			{ name: 'Decimal', value: 'decimal' },
			{ name: 'Integer', value: 'integer' },
			{ name: 'Text', value: 'text' },
		],
		default: 'text',
		displayOptions: {
			show: {
				resource: ['label'],
				operation: ["create"],
			},
		},
	},
	{
		displayName: 'Label Name or ID',
		name: 'label_id',
		type: 'options',
		required: true,
		typeOptions: {
			loadOptionsMethod: 'getLabels',
		},
		default: '',
		displayOptions: {
			show: {
				resource: ['label'],
				operation: ["update", "delete", "unlabel_customer", "unlabel_member", "unlabel_resource", "unlabel_proposal", "unlabel_work_item", "unlabel_operational_item"],
			},
		},
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
	},
	{
		displayName: 'Org',
		name: 'org',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['label'],
				operation: ["label_customer"],
			},
		},
	},
	{
		displayName: 'Label Name or ID',
		name: 'label',
		type: 'options',
		required: true,
		typeOptions: {
			loadOptionsMethod: 'getLabels',
		},
		default: '',
		displayOptions: {
			show: {
				resource: ['label'],
				operation: ["label_customer", "label_member", "label_resource", "label_proposal", "label_work_item", "label_operational_item"],
			},
		},
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
	},
	{
		displayName: 'Value Text',
		name: 'value_text',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['label'],
				operation: ["label_customer", "label_member", "label_resource", "label_proposal", "label_work_item", "label_operational_item"],
			},
		},
	},
	{
		displayName: 'Value Integer',
		name: 'value_integer',
		type: 'number',
		default: 0,
		displayOptions: {
			show: {
				resource: ['label'],
				operation: ["label_customer", "label_member", "label_resource", "label_proposal", "label_work_item", "label_operational_item"],
			},
		},
	},
	{
		displayName: 'Value Decimal',
		name: 'value_decimal',
		type: 'number',
		default: 0,
		displayOptions: {
			show: {
				resource: ['label'],
				operation: ["label_customer", "label_member", "label_resource", "label_proposal", "label_work_item", "label_operational_item"],
			},
		},
	},
	{
		displayName: 'Value Date',
		name: 'value_date',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['label'],
				operation: ["label_customer", "label_member", "label_resource", "label_proposal", "label_work_item", "label_operational_item"],
			},
		},
	},
	{
		displayName: 'Org Name or ID',
		name: 'org_id',
		type: 'options',
		required: true,
		typeOptions: {
			loadOptionsMethod: 'getCustomers',
		},
		default: '',
		displayOptions: {
			show: {
				resource: ['label'],
				operation: ["unlabel_customer"],
			},
		},
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
	},
	{
		displayName: 'Team',
		name: 'team',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['label'],
				operation: ["label_member"],
			},
		},
	},
	{
		displayName: 'Member Name or ID',
		name: 'member_id',
		type: 'options',
		required: true,
		typeOptions: {
			loadOptionsMethod: 'getMembers',
		},
		default: '',
		displayOptions: {
			show: {
				resource: ['label'],
				operation: ["unlabel_member"],
			},
		},
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
	},
	{
		displayName: 'Resource',
		name: 'resource',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['label'],
				operation: ["label_resource"],
			},
		},
	},
	{
		displayName: 'Resource ID',
		name: 'resource_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['label'],
				operation: ["unlabel_resource"],
			},
		},
	},
	{
		displayName: 'Proposal',
		name: 'proposal',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['label'],
				operation: ["label_proposal"],
			},
		},
	},
	{
		displayName: 'Proposal Name or ID',
		name: 'proposal_id',
		type: 'options',
		required: true,
		typeOptions: {
			loadOptionsMethod: 'getProposals',
		},
		default: '',
		displayOptions: {
			show: {
				resource: ['label'],
				operation: ["unlabel_proposal"],
			},
		},
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
	},
	{
		displayName: 'Work Item',
		name: 'work_item',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['label'],
				operation: ["label_work_item", "label_operational_item"],
			},
		},
	},
	{
		displayName: 'Work Item ID',
		name: 'work_item_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['label'],
				operation: ["unlabel_work_item", "unlabel_operational_item"],
			},
		},
	},
];
