// Auto-generated by generate_n8n.py — do not edit manually.
import type { INodeProperties } from 'n8n-workflow';

export const locationOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: { resource: ['location'] },
		},
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a location',
				description: 'Create a new location',
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a location',
				description: 'Delete a location',
			},
			{
				name: 'List All',
				value: 'list',
				action: 'List all locations',
				description: 'List all locations in the workspace',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a location',
				description: 'Update a location',
			},
		],
		default: 'create',
	},
];

export const locationFields: INodeProperties[] = [
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['location'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Description',
		name: 'description',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['location'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Internal Code',
		name: 'internal_code',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['location'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Country',
		name: 'country',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['location'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Parent',
		name: 'parent',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['location'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Is Active',
		name: 'is_active',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: {
				resource: ['location'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Location ID',
		name: 'location_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['location'],
				operation: ["update", "delete"],
			},
		},
	},
];
