// Auto-generated by generate_n8n.py — do not edit manually.
import type { INodeProperties } from 'n8n-workflow';

export const paymentOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: { resource: ['payment'] },
		},
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a payment',
				description: 'Create a new payment record',
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a payment',
				description: 'Delete a payment',
			},
			{
				name: 'Mark Paid',
				value: 'mark_paid',
				action: 'Mark a payment as paid',
				description: 'Mark a payment as paid',
			},
			{
				name: 'Mark Unpaid',
				value: 'mark_unpaid',
				action: 'Mark a payment as unpaid',
				description: 'Mark a payment as unpaid',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a payment',
				description: 'Update an existing payment',
			},
		],
		default: 'create',
	},
];

export const paymentFields: INodeProperties[] = [
	{
		displayName: 'Payment Schedule Block ID',
		name: 'payment_schedule_block_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['payment'],
				operation: ["create"],
			},
		},
	},
	{
		displayName: 'Product ID',
		name: 'product_id',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['payment'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['payment'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Internal Code',
		name: 'internal_code',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['payment'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Due Date',
		name: 'due_date',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['payment'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Amount',
		name: 'amount',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: {
			show: {
				resource: ['payment'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Payment Integration ID',
		name: 'payment_integration_id',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['payment'],
				operation: ["create", "update", "mark_paid"],
			},
		},
	},
	{
		displayName: 'Payment ID',
		name: 'payment_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['payment'],
				operation: ["update", "mark_paid", "mark_unpaid", "delete"],
			},
		},
	},
	{
		displayName: 'Paid Date',
		name: 'paid_date',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['payment'],
				operation: ["mark_paid"],
			},
		},
	},
];
