// Auto-generated by generate_n8n.py — do not edit manually.
import type { INodeProperties } from 'n8n-workflow';

export const projectOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: { resource: ['project'] },
		},
		options: [
			{
				name: 'Get Work Items',
				value: 'get_work_items',
				action: 'Get project work items',
				description: 'Get all work items for a project',
			},
			{
				name: 'List All',
				value: 'list',
				action: 'List all projects',
				description: 'List all projects',
			},
		],
		default: 'get_work_items',
	},
];

export const projectFields: INodeProperties[] = [
	{
		displayName: 'Project Name or ID',
		name: 'project_id',
		type: 'options',
		required: true,
		typeOptions: {
			loadOptionsMethod: 'getProjects',
		},
		default: '',
		displayOptions: {
			show: {
				resource: ['project'],
				operation: ["get_work_items"],
			},
		},
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
	},
];
