// Auto-generated by generate_n8n.py — do not edit manually.
import type { INodeProperties } from 'n8n-workflow';

export const proposalOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: { resource: ['proposal'] },
		},
		options: [
			{
				name: 'Change Stage',
				value: 'change_stage',
				action: 'Change proposal stage',
				description: 'Move a proposal to a different pipeline stage',
			},
			{
				name: 'Create',
				value: 'create',
				action: 'Create a proposal',
				description: 'Create a new proposal',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a proposal',
				description: 'Get a single proposal by ID',
			},
			{
				name: 'List',
				value: 'list',
				action: 'List proposals',
				description: 'List proposals for an organization',
			},
			{
				name: 'Reopen',
				value: 'reopen',
				action: 'Reopen a proposal',
				description: 'Reopen a closed proposal',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a proposal',
				description: 'Update an existing proposal',
			},
		],
		default: 'change_stage',
	},
];

export const proposalFields: INodeProperties[] = [
	{
		displayName: 'Org Name or ID',
		name: 'org_id',
		type: 'options',
		required: true,
		typeOptions: {
			loadOptionsMethod: 'getCustomers',
		},
		default: '',
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["list"],
			},
		},
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
	},
	{
		displayName: 'Proposal Name or ID',
		name: 'proposal_id',
		type: 'options',
		required: true,
		typeOptions: {
			loadOptionsMethod: 'getProposals',
		},
		default: '',
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["get", "update", "change_stage", "reopen"],
			},
		},
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
	},
	{
		displayName: 'Internal Code',
		name: 'internal_code',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Description',
		name: 'description',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Customer',
		name: 'customer',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Rfp Publication',
		name: 'rfp_publication',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Owner Name or ID',
		name: 'owner',
		type: 'options',
		required: true,
		typeOptions: {
			loadOptionsMethod: 'getMembers',
		},
		default: '',
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
	},
	{
		displayName: 'Manager Name or ID',
		name: 'manager',
		type: 'options',
		required: true,
		typeOptions: {
			loadOptionsMethod: 'getMembers',
		},
		default: '',
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create"],
			},
		},
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
	},
	{
		displayName: 'Sales Stage',
		name: 'sales_stage',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create"],
			},
		},
	},
	{
		displayName: 'Proposal Currency',
		name: 'proposal_currency',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Pricing Strategy',
		name: 'pricing_strategy',
		type: 'options',
		options: [
			{ name: 'Fixed Amount', value: 'fixed_amount' },
			{ name: 'Margin Target', value: 'margin_target' },
			{ name: 'Percentage', value: 'percentage' },
			{ name: 'Product Prices', value: 'product_prices' },
		],
		default: 'product_prices',
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Pricing Adjustment Percent',
		name: 'pricing_adjustment_percent',
		type: 'number',
		default: 0,
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Pricing Adjustment Amount',
		name: 'pricing_adjustment_amount',
		type: 'number',
		default: 0,
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Target Margin Percent',
		name: 'target_margin_percent',
		type: 'number',
		default: 0,
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Minimum Margin Percent',
		name: 'minimum_margin_percent',
		type: 'number',
		default: 0,
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Proposal Valid Since',
		name: 'proposal_valid_since',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Proposal Valid Until',
		name: 'proposal_valid_until',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Project Start Date',
		name: 'project_start_date',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Project End Date',
		name: 'project_end_date',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Project Enable Booking Management',
		name: 'project_enable_booking_management',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Project Enable Resource Management',
		name: 'project_enable_resource_management',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Project Enable Effort Management',
		name: 'project_enable_effort_management',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Project Enable Financial Management',
		name: 'project_enable_financial_management',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Project Enable Schedule Management',
		name: 'project_enable_schedule_management',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Project Enable Earned Value Management',
		name: 'project_enable_earned_value_management',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Wbsconfiguration',
		name: 'wbsconfiguration',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Stage ID',
		name: 'stage_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["change_stage"],
			},
		},
	},
	{
		displayName: 'I Have Followed The Instructions',
		name: 'i_have_followed_the_instructions',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["change_stage"],
			},
		},
	},
	{
		displayName: 'Contact ID',
		name: 'contact_id',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["change_stage"],
			},
		},
	},
	{
		displayName: 'Rejection Reason',
		name: 'rejection_reason',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['proposal'],
				operation: ["change_stage"],
			},
		},
	},
];
