// Auto-generated by generate_n8n.py — do not edit manually.
import type { INodeProperties } from 'n8n-workflow';

export const resourceOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: { resource: ['resource'] },
		},
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a resource',
				description: 'Create a new resource',
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a resource',
				description: 'Delete a resource',
			},
			{
				name: 'List All',
				value: 'list',
				action: 'List all resources',
				description: 'List all resources in the workspace',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a resource',
				description: 'Update a resource',
			},
		],
		default: 'create',
	},
];

export const resourceFields: INodeProperties[] = [
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['resource'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Internal Code',
		name: 'internal_code',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['resource'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Description',
		name: 'description',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['resource'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Parent',
		name: 'parent',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['resource'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Timezone',
		name: 'timezone',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['resource'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Resource ID',
		name: 'resource_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['resource'],
				operation: ["update", "delete"],
			},
		},
	},
];
