// Auto-generated by generate_n8n.py — do not edit manually.
import type { INodeProperties } from 'n8n-workflow';

export const teamMemberOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: { resource: ['teamMember'] },
		},
		options: [
			{
				name: 'Edit',
				value: 'edit',
				action: 'Edit a team member',
				description: 'Edit a team member\'s preferences',
			},
			{
				name: 'Invite',
				value: 'invite',
				action: 'Invite a team member',
				description: 'Invite someone to join the team',
			},
			{
				name: 'List All',
				value: 'list',
				action: 'List all team members',
				description: 'List all team members',
			},
			{
				name: 'Remove',
				value: 'remove',
				action: 'Remove a team member',
				description: 'Remove a member from the team',
			},
		],
		default: 'edit',
	},
];

export const teamMemberFields: INodeProperties[] = [
	{
		displayName: 'Email',
		name: 'email',
		type: 'string',
		required: true,
		placeholder: 'name@email.com',
		default: '',
		displayOptions: {
			show: {
				resource: ['teamMember'],
				operation: ["invite"],
			},
		},
	},
	{
		displayName: 'Member Name or ID',
		name: 'member_id',
		type: 'options',
		required: true,
		typeOptions: {
			loadOptionsMethod: 'getMembers',
		},
		default: '',
		displayOptions: {
			show: {
				resource: ['teamMember'],
				operation: ["edit"],
			},
		},
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
	},
	{
		displayName: 'Nickname',
		name: 'nickname',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['teamMember'],
				operation: ["edit"],
			},
		},
	},
	{
		displayName: 'Work Email',
		name: 'work_email',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['teamMember'],
				operation: ["edit"],
			},
		},
	},
	{
		displayName: 'Work Email Alternative',
		name: 'work_email_alternative',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['teamMember'],
				operation: ["edit"],
			},
		},
		description: 'Email address visible to customers in their portal',
	},
	{
		displayName: 'Work Phone',
		name: 'work_phone',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['teamMember'],
				operation: ["edit"],
			},
		},
	},
	{
		displayName: 'Work Phone Alternative',
		name: 'work_phone_alternative',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['teamMember'],
				operation: ["edit"],
			},
		},
		description: 'Phone number visible to customers in their portal',
	},
	{
		displayName: 'Territory',
		name: 'territory',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['teamMember'],
				operation: ["edit"],
			},
		},
	},
	{
		displayName: 'Team Name or ID',
		name: 'team_id',
		type: 'options',
		required: true,
		typeOptions: {
			loadOptionsMethod: 'getMembers',
		},
		default: '',
		displayOptions: {
			show: {
				resource: ['teamMember'],
				operation: ["remove"],
			},
		},
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
	},
];
