// Auto-generated by generate_n8n.py — do not edit manually.
import type { INodeProperties } from 'n8n-workflow';

export const webhookOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: { resource: ['webhook'] },
		},
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a webhook',
				description: 'Create a new webhook subscription',
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a webhook',
				description: 'Delete a webhook subscription',
			},
			{
				name: 'List All',
				value: 'list',
				action: 'List all webhooks',
				description: 'List all webhooks',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a webhook',
				description: 'Update a webhook subscription',
			},
		],
		default: 'create',
	},
];

export const webhookFields: INodeProperties[] = [
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['webhook'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Target Url',
		name: 'target_url',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['webhook'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Event Types',
		name: 'event_types',
		type: 'json',
		default: '',
		displayOptions: {
			show: {
				resource: ['webhook'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Is Active',
		name: 'is_active',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: {
				resource: ['webhook'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Is Secure',
		name: 'is_secure',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: {
				resource: ['webhook'],
				operation: ["create", "update"],
			},
		},
	},
	{
		displayName: 'Webhook ID',
		name: 'webhook_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['webhook'],
				operation: ["update", "delete"],
			},
		},
	},
];
