// Auto-generated by generate_n8n.py — do not edit manually.
import { createHmac } from 'crypto';
import type {
	IHookFunctions,
	IWebhookFunctions,
	INodeType,
	INodeTypeDescription,
	IWebhookResponseData,
} from 'n8n-workflow';

const SIGNATURE_HEADER = 'x-webhook-signature';
const MAX_AGE_SECONDS = 300; // 5 minutes — reject older payloads (replay protection)

function verifySignature(secret: string, signature: string, rawBody: string): boolean {
	// Format: t={timestamp},v1={hex_digest}
	const parts: Record<string, string> = {};
	for (const pair of signature.split(',')) {
		const idx = pair.indexOf('=');
		if (idx > 0) {
			parts[pair.slice(0, idx)] = pair.slice(idx + 1);
		}
	}

	const timestamp = parts.t;
	const v1 = parts.v1;
	if (!timestamp || !v1) return false;

	// Replay protection
	const age = Math.floor(Date.now() / 1000) - parseInt(timestamp, 10);
	if (isNaN(age) || age > MAX_AGE_SECONDS || age < -MAX_AGE_SECONDS) return false;

	// Verify HMAC-SHA256: sign("{timestamp}.{body}")
	const expected = createHmac('sha256', secret)
		.update(`${timestamp}.${rawBody}`)
		.digest('hex');

	// Constant-time comparison
	if (expected.length !== v1.length) return false;
	let mismatch = 0;
	for (let i = 0; i < expected.length; i++) {
		mismatch |= expected.charCodeAt(i) ^ v1.charCodeAt(i);
	}
	return mismatch === 0;
}

export class ProiectroTrigger implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'Proiect.ro Trigger',
		name: 'proiectroTrigger',
		icon: 'file:proiectro.svg',
		group: ['trigger'],
		version: 1,
		usableAsTool: true,
		subtitle: '={{$parameter["eventType"]}}',
		description: 'Starts the workflow when a Proiect.ro event occurs',
		defaults: { name: 'Proiect.ro Trigger' },
		inputs: [],
		outputs: ['main'],
		credentials: [{ name: 'proiectroApi', required: true }],
		webhooks: [
			{
				name: 'default',
				httpMethod: 'POST',
				responseMode: 'onReceived',
				path: 'webhook',
			},
		],
		properties: [
			{
				displayName: 'Event Type',
				name: 'eventType',
				type: 'multiOptions',
				required: true,
				default: [],
				options: [
					{ name: 'Contact Created', value: 'addContact' },
					{ name: 'Contact Deleted', value: 'deleteContact' },
					{ name: 'Contact Updated', value: 'editContact' },
					{ name: 'Customer Created', value: 'addOrg' },
					{ name: 'Customer Deleted', value: 'deleteOrg' },
					{ name: 'Customer Labeled', value: 'labelOrg' },
					{ name: 'Customer Tagged', value: 'tagOrg' },
					{ name: 'Customer Unlabeled', value: 'unlabelOrg' },
					{ name: 'Customer Untagged', value: 'untagOrg' },
					{ name: 'Customer Updated', value: 'editOrg' },
					{ name: 'Label Created', value: 'addLabel' },
					{ name: 'Label Deleted', value: 'deleteLabel' },
					{ name: 'Label Updated', value: 'editLabel' },
					{ name: 'Operational Work Item Tagged', value: 'tagOperationalWorkItem' },
					{ name: 'Operational Work Item Untagged', value: 'untagOperationalWorkItem' },
					{ name: 'Payment Created', value: 'addPayment' },
					{ name: 'Payment Deleted', value: 'deletePayment' },
					{ name: 'Payment Marked Paid', value: 'markPaymentPaid' },
					{ name: 'Payment Marked Unpaid', value: 'markPaymentUnpaid' },
					{ name: 'Payment Updated', value: 'editPayment' },
					{ name: 'Process Created', value: 'addProcess' },
					{ name: 'Process Deleted', value: 'deleteProcess' },
					{ name: 'Process Updated', value: 'editProcess' },
					{ name: 'Proposal Accepted', value: 'acceptProposal' },
					{ name: 'Proposal Created', value: 'addProposal' },
					{ name: 'Proposal Labeled', value: 'labelProposal' },
					{ name: 'Proposal Stage Changed', value: 'changeProposalStage' },
					{ name: 'Proposal Tagged', value: 'tagProposal' },
					{ name: 'Proposal Unlabeled', value: 'unlabelProposal' },
					{ name: 'Proposal Untagged', value: 'untagProposal' },
					{ name: 'Proposal Updated', value: 'editProposal' },
					{ name: 'Resource Created', value: 'addResource' },
					{ name: 'Resource Deleted', value: 'deleteResource' },
					{ name: 'Resource Labeled', value: 'labelResource' },
					{ name: 'Resource Tagged', value: 'tagResource' },
					{ name: 'Resource Unlabeled', value: 'unlabelResource' },
					{ name: 'Resource Untagged', value: 'untagResource' },
					{ name: 'Resource Updated', value: 'editResource' },
					{ name: 'Support Request Created', value: 'addInternalSupportRequest' },
					{ name: 'Tag Created', value: 'addTag' },
					{ name: 'Tag Deleted', value: 'deleteTag' },
					{ name: 'Tag Updated', value: 'editTag' },
					{ name: 'Team Member Invited', value: 'inviteToTeam' },
					{ name: 'Team Member Labeled', value: 'labelMember' },
					{ name: 'Team Member Removed', value: 'excludeFromTeam' },
					{ name: 'Team Member Tagged', value: 'tagMember' },
					{ name: 'Team Member Unlabeled', value: 'unlabelMember' },
					{ name: 'Team Member Untagged', value: 'untagMember' },
					{ name: 'Webhook Created', value: 'addWebhookEndpoint' },
					{ name: 'Webhook Deleted', value: 'deleteWebhookEndpoint' },
					{ name: 'Webhook Updated', value: 'editWebhookEndpoint' },
					{ name: 'Work Item Approved', value: 'approveOperationalItem' },
					{ name: 'Work Item Created', value: 'addOperationalItem' },
					{ name: 'Work Item Created (Project)', value: 'addWorkItem' },
					{ name: 'Work Item Deleted', value: 'deleteOperationalItem' },
					{ name: 'Work Item Labeled', value: 'labelWorkItem' },
					{ name: 'Work Item Moved', value: 'moveOperationalItem' },
					{ name: 'Work Item Reassigned', value: 'reassignOperationalItem' },
					{ name: 'Work Item Rejected', value: 'rejectOperationalItem' },
					{ name: 'Work Item Status Changed', value: 'updateWorkItemStatus' },
					{ name: 'Work Item Tagged (Project)', value: 'tagProjectWorkItem' },
					{ name: 'Work Item Unlabeled', value: 'unlabelWorkItem' },
					{ name: 'Work Item Untagged (Project)', value: 'untagProjectWorkItem' },
					{ name: 'Work Item Updated', value: 'editOperationalItem' },
					{ name: 'Work Item Updated (Project)', value: 'editWorkItem' },
				],
				description: 'The event types to listen for',
			},
		],
	};

	webhookMethods = {
		default: {
			async checkExists(this: IHookFunctions): Promise<boolean> {
				const webhookData = this.getWorkflowStaticData('node');
				return !!webhookData.webhookId;
			},

			async create(this: IHookFunctions): Promise<boolean> {
				const webhookUrl = this.getNodeWebhookUrl('default');
				const eventTypes = this.getNodeParameter('eventType') as string[];
				const credentials = await this.getCredentials('proiectroApi');

				const response = (await this.helpers.httpRequest({
					method: 'POST',
					url: `${credentials.baseUrl}/api/v1/${credentials.workspacePath}/add_webhook`,
					headers: {
						Authorization: `Bearer ${credentials.apiKey}`,
						'Content-Type': 'application/json',
					},
					body: {
						name: `n8n: ${this.getWorkflow().name}`,
						target_url: webhookUrl,
						event_types: eventTypes,
						is_active: true,
						is_secure: true,
					},
				})) as { webhook_id: string; secret_key: string };

				const webhookData = this.getWorkflowStaticData('node');
				webhookData.webhookId = response.webhook_id;
				webhookData.secretKey = response.secret_key;
				return true;
			},

			async delete(this: IHookFunctions): Promise<boolean> {
				const webhookData = this.getWorkflowStaticData('node');
				const credentials = await this.getCredentials('proiectroApi');

				if (webhookData.webhookId) {
					try {
						await this.helpers.httpRequest({
							method: 'DELETE',
							url: `${credentials.baseUrl}/api/v1/${credentials.workspacePath}/delete_webhook/${webhookData.webhookId}`,
							headers: {
								Authorization: `Bearer ${credentials.apiKey}`,
							},
						});
					} catch {
						// Webhook may already be deleted — ignore cleanup errors
					}
				}
				delete webhookData.webhookId;
				delete webhookData.secretKey;
				return true;
			},
		},
	};

	async webhook(this: IWebhookFunctions): Promise<IWebhookResponseData> {
		const req = this.getRequestObject();
		const webhookData = this.getWorkflowStaticData('node');
		const secret = webhookData.secretKey as string | undefined;

		if (secret) {
			const signature = this.getHeaderData()[SIGNATURE_HEADER] as string | undefined;
			if (!signature) {
				return { webhookResponse: 'Missing signature', workflowData: undefined };
			}
			// Use the raw body for signature verification
			const rawBody = typeof req.rawBody === 'string'
				? req.rawBody
				: (req.rawBody as Buffer).toString('utf-8');
			if (!verifySignature(secret, signature, rawBody)) {
				return { webhookResponse: 'Invalid signature', workflowData: undefined };
			}
		}

		const bodyData = this.getBodyData();
		return {
			workflowData: [this.helpers.returnJsonArray(bodyData)],
		};
	}
}
